name: pos_app
description: an app for demonstration
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.10.0
  image_picker: ^0.6.7+14
  qr_flutter: ^3.2.0
  google_maps_flutter: ^1.0.6
  location: ^3.1.0
  printing: ^3.7.1
  path_provider: ^1.6.24
  flutter_blue: ^0.7.3
  blue_thermal_printer: ^1.1.1
  image: ^2.1.19
  tutorial_coach_mark: ^0.5.2
  flutter_image_compress: ^0.7.0
  file_picker: ^2.1.4
  localstorage: ^3.0.6+9
  provider: ^4.3.2+3
  flutter_email_sender: ^4.0.0
  pdf: ^1.13.0
  marquee: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/product/